### ISSUE TITLE
Can not specify port of https in latest OpenPli release

### ISSUE THREAD

**Issue by chrislin3054** [OpenPLi/enigma2#1007]
Can not specify port of https in latest OpenPli release. Please check below log:

f = urllib2.urlopen("https://www.baidu.com:443/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usrb/python2.7/urllib2.py", line 126, in urlopen
  File "/usrb/python2.7/urllib2.py", line 400, in open
  File "/usrb/python2.7/urllib2.py", line 418, in _open
  File "/usrb/python2.7/urllib2.py", line 378, in _call_chain
  File "/usrb/python2.7/urllib2.py", line 1215, in https_open
  File "/usrb/python2.7/urllib2.py", line 1177, in do_open
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by WanWizard** [comment]
"Name or service not known" is a DNS error. 

It might also be a proxy issue (proxy defined or not defined), in which cause you can use
`os.environ['http_proxy'] = ...
`before the urllib2 call to fix that.

Please note that we don't provide support using github issues, please visit our forum at https://forums.openpli.org and ask your questions there.
