### ISSUE TITLE
Virtual Keyboard crash on skins different from OpenPLi

### ISSUE THREAD

**Issue by lprot** [OpenPLi/enigma2#1695]
```
Taapat based on OpenPLi Enigma2 crash log

crashdate=Sun Aug 26 17:50:34 2018
compiledate=Aug 25 2018
skin=LiteHD/skin.xml
sourcedate=2018-08-25
branch=develop
rev=8a0ab02
component=Enigma2

stbmodel=spark
kernelcmdline=console=ttyAS0,115200 root=/dev/mtdblock6 rw rootfstype=jffs2 init=/bin/devinit coprocessor_mem=4m@0x40000000,4m@0x40400000 printk=1 stmmaceth=ethaddr:24:00:07:01:8F:E2
nimsockets=NIM Socket 0:
imageversion=openpli pli-extras \n \l
imageissue=openpli pli-extras %h


REMOVE Peer spark
REMOVE Peer spark
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 49, in action
  File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeSearch.py", line 243, in openKeyboard
  File "/usr/lib/enigma2/python/mytest.py", line 287, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 297, in open
    dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 240, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
  File "/usr/lib/enigma2/python/mytest.py", line 264, in doInstantiateDialog
    dlg.applySkin()
  File "/usr/lib/enigma2/python/Components/GUISkin.py", line 154, in applySkin
  File "/usr/lib/enigma2/python/Components/GUISkin.py", line 57, in createGUIScreen
  File "/usr/lib/enigma2/python/Screens/VirtualKeyBoard.py", line 602, in buildVirtualKeyBoard
  File "/usr/lib/enigma2/python/Screens/VirtualKeyBoard.py", line 633, in markSelectedKey
AttributeError: 'NoneType' object has no attribute 'size'


dmesg

 kept as earlytimer
<6>usbcore: registered new interface driver usbhid
<6>usbhid: v2.6:USB HID core driver
<4>STMicroelectronics - Coprocessors st231 Init
<4>st231.0 Coprocessor -------------------------------------------
<4>    flags 0001 RAM start at 0xa0000000  size      0x00400000
<4>                  cop. addr 0x40000000
<4>    Channels : Not defined
<4>    IRQ      : not used
<4>---------------------------------------------------------------
<4>st231.1 Coprocessor -------------------------------------------
<4>    flags 0001 RAM start at 0xa0400000  size      0x00400000
<4>                  cop. addr 0x40400000
<4>    Channels : Not defined
<4>    IRQ      : not used
<4>---------------------------------------------------------------
<6>DMA: Registering fdma_dmac.0 handler (16 channels).
<4>IRQ 140/fdma_dmac.0: IRQF_DISABLED is not guaranteed on shared IRQs
<6>stm-fdma stm-fdma.0: firmware: using built-in firmware fdma_STx7111_0.elf
<6>DMA: Registering fdma_dmac.1 handler (16 channels).
<6>platform fdma_dmac.0: SLIM hw 0.0, FDMA fw 2.3
<4>IRQ 141/fdma_dmac.1: IRQF_DISABLED is not guaranteed on shared IRQs
<6>stm-fdma stm-fdma.1: firmware: using built-in firmware fdma_STx7111_1.elf
<6>platform fdma_dmac.1: SLIM hw 0.0, FDMA fw 2.6
<6>Advanced Linux Sound Architecture Driver Version 1.0.21.
<6>ALSA device list:
<6>  #0: STMicroelectronics STx7111 cut 3.x SOC audio subsystem
<6>TCP cubic registered
<6>NET: Registered protocol family 10
<6>NET: Registered protocol family 17
<6>lib80211: common routines for IEEE802.11 drivers
<7>lib80211_crypt: registered algorithm 'NULL'
<6>usb 1-1: new high speed USB device using stm-ehci and address 2
<6>usb 1-1: configuration #1 chosen from 1 choice
<6>scsi0 : SCSI emulation for USB Mass Storage devices
<7>usb-storage: device found at 2
<7>usb-storage: waiting for device to settle before scanning
<5>scsi 0:0:0:0: Direct-Access     Generic  Flash Disk       8.01 PQ: 0 ANSI: 2
<5>sd 0:0:0:0: [sda] 8224768 512-byte logical blocks: (4.21 GB/3.92 GiB)
<5>sd 0:0:0:0: [sda] Write Protect is off
<7>usb-storage: device scan complete
<7>sd 0:0:0:0: [sda] Mode Sense: 03 00 00 00
<3>sd 0:0:0:0: [sda] Assuming drive cache: write through
<3>sd 0:0:0:0: [sda] Assuming drive cache: write through
<6> sda: sda1 sda2
<3>sd 0:0:0:0: [sda] Assuming drive cache: write through
<5>sd 0:0:0:0: [sda] Attached SCSI removable disk
<4>VFS: Mounted root (jffs2 filesystem) on device 31:6.
<6>devtmpfs: mounted
<4>Freeing unused kernel memory: 124k freed
<6>EXT4-fs (sda1): mounted filesystem with ordered data mode
<6>Adding 89080k swap on /dev/sda2.  Priority:-1 extents:1 across:89080k 
<6>stmcore-display: using HDMI hotplug
<6>stmcore-display: STi7111 display probed
<3>device probe found 2 display pipelines
<4>requesting frm: 'component.fw', c11ff16c/896e9d50
<6> stm-awg: firmware: requesting component.fw
<4>frm 'component.fw' successfully loaded
<4>requesting frm: 'fdvo0.fw', c11ff16c/89754290
<6> stm-awg: firmware: requesting fdvo0.fw
<4>loading frm: 'fdvo0.fw' failed: -2
<4>[CEC] init - starting
<4>[CEC] The above error is a wanted behaviour as this was a ping!
<4>Fulan front panel driver
<4>VfdType = 2
<4>CpuType = 2
<4>DisplayInfo = 4
<4>scankeyNum = 8
<4>swMajorVersion = 1
<4>swSubVersion = 13
<4>stby key 0 = a25d7887
<4>stby key 1 = 00000000
<4>stby key 2 = 00000000
<4>stby key 3 = 00000000
<4>stby key 4 = 00000000
<4>blue key 0 = a25d52ad
<4>blue key 1 = 00000000
<4>blue key 2 = 00000000
<4>blue key 3 = 00000000
<4>blue key 4 = 00000000
<6>input: fulan front panel buttons as /devices/virtual/input/input0
<6>aotom-rtc aotom-rtc: rtc core: registered aotom as rtc0
<7>aotom_rtc_probe 8974c200
<7>aotom_rtc_probe 2
<4>stmfb: fb0 parameters = "1280x720-32@50:16m:pal:yuv:yuv"
<4>stmfb: fb1 parameters = "<NULL>"
<4>Init of MME log wrapper
<4>stm_v4l2_register_driver: driver 'stmvout' registered
<4>stm_v4l2_register_driver: driver 'stmvbi' registered
<6>snd_pseudo snd_pseudo.0: firmware: requesting downmix.fw
<6>pseudocard: 1 pseudo soundcard(s) found
<4>stv090x loaded
<4>pti: module license 'NO' taints kernel.
<4>Disabling lock debugging due to kernel taint
<6>DVB: registering new adapter (STM Streamer)
<6>stv090x_register_frontend: stv090x DVB: 0.11 
<4>tuner = 1
<4>stv090x_register_frontend: init tuner 0
<4>> (bus = 3) init_stv090x_device
<4>i2c adapter = 0x89657018
<4>i2c addr = 68
<4>tuner enable = 0.0
<6>frontend_init >
<4>tuner_Sharp7903 is Identified
<4>frontend_init: attached
<4>vz7903_attach: Attaching vz7903 tuner
<4>frontend_init: vz7903_attach
<4>stv090x_init: AGCRF1CFG = 0x10
<4>stv090x_init: AGCRF2CFG = 0x13
<6>init_stv090x_device: Call dvb_register_frontend (adapter = 0x894b603c)
<4>DVB: registering adapter 0 frontend 0 (STV090x Multistandard)...
<6>stv090x_register_frontend: <
<4>install_e2_procs(): entry already in use 'progress'
<4>install_e2_procs(): entry already in use 'stb/fp/was_timer_wakeup'
<4>stm_v4l2_register_driver: driver 'Linux DVB Overlay' registered
<4>OSDEV_LinkDevice - /dev/allocator, Major 245, Minor 0
<4>AllocatorLoadModule : Allocator device loaded
<4>OSDEV_LinkDevice - /dev/h264pp, Major 246, Minor 0
<4>H264ppLoadModule : H264pp device loaded
<4>(bpamem_init): BPAMem driver register result = 0
<4>[simu_button] initializing ...
<4>[simu_button] allocating and registering button device
<6>input: TDT RC event driver as /devices/virtual/input/input1
<4>Registering device 'sc', major '169'
<4>Version of smartcard driver: [1.0.1]
<6>ramzswap: disk size not provided. You can use disksize_kb module param to specify size.
<6>Using default: (25% of RAM).
<6>ramzswap: disk size set to 35528 kB
<6>ramzswap: Initialization done!
<6>Adding 35524k swap on /dev/ramzswap0.  Priority:100 extents:1 across:35524k SS
<7>yaffs: yaffs built Aug 23 2018 12:21:44 Installing.
<6>yaffs: dev is 32505860 name is "mtdblock4" rw
<6>yaffs: passed flags ""
<7>yaffs: yaffs: Attempting MTD mount of 31.4,"mtdblock4"
<7>yaffs: yaffs_read_super: is_checkpointed 1
<4>PARSE CMDLINE: 24:00:07:01:8F:E2
<4>ETHADDR: 24:00:07:01:8F:E2
<4>eth0: device MAC address 24:00:07:01:8f:e2
<6> No MAC Management Counters available
<6>PHY: 0:01 - Link is Up - 100/Full
<6>input: remote control as /devices/virtual/input/input2
<7>eth0: no IPv6 routers present
<4>VFD/AOTOM: unknown IOCTL 0x1015
<4>stmhdmiio_get_cec_address - 88d40000
<4>stv090x_init: AGCRF1CFG = 0x10
<4>stv090x_init: AGCRF2CFG = 0x13
<4>aotom_write_rtc_offset 4 - aotom_write_rtc_offset -> 7200
<4> offset: 7200
<4>stmhdmiio_set_audio_source - 88d40000
<4>power_standbyled_write(2, ononstmhdmiio_set_edid_handling - 88d40000
<6>ramzswap: Read before write on swap device: sector=70912, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=8, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=16, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=24, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=32, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=40, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=48, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=56, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=64, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=72, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=80, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=88, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=96, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=104, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=112, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=120, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=128, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=136, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=144, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=152, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=160, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=168, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=176, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=184, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=192, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=200, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=208, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=216, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=224, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=232, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=240, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=248, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=256, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=264, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=272, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=280, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=288, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=296, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=304, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=312, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=320, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=328, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=336, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=344, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=352, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=360, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=368, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=376, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=384, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=392, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=400, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=408, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=416, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=424, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=432, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=440, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=448, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=456, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=464, size=4096, offset=0
<6>ramzswap: Read before write on swap device: sector=472, size=4096, offset=0
<4>stmhdmiio_set_audio_source - 88d40000
<4>stmhdmiio_get_cec_address - 88d40000
<4>stv090x_init: AGCRF1CFG = 0x10
<4>stv090x_init: AGCRF2CFG = 0x13
<6>NFS: bad mount option value specified: vers=4.2
<6>NFS: bad mount option value specified: vers=4.1
<6>NFS: bad mount option value specified: vers=4.0
<6>NFS: bad mount option value specified: vers=4.2
<6>NFS: bad mount option value specified: vers=4.1
<6>NFS: bad mount option value specified: vers=4.0
<4>[tuner vz7903]beta=62 alpha=92000 M=92062 A=3 N=20 sd=fdf3
<4>i_data1 = 2 XtalFreqKHz=16000
<4>vz7903_set_frequency: Frequency=1473 symbolrate=27500
<4>[nim_vz7903_status tuner_id = 0]
<4>vz7903_get_frequency: Frequency=1473000
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03f12 ins=0x6551
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fefd0 ins=0x8501
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fef8a ins=0x6152
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03f12 ins=0x6551
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fefd0 ins=0x8501
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03f12 ins=0x6551
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fefd0 ins=0x8501
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03f12 ins=0x6551
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fefd0 ins=0x8501
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01fac ins=0x6911
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01e06 ins=0x6171
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01e22 ins=0x8571
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03f12 ins=0x6551
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fefd0 ins=0x8501
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fef8a ins=0x6152
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01fac ins=0x6911
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01e06 ins=0x6171
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01e22 ins=0x8571
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03f12 ins=0x6551
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fefd0 ins=0x8501
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fef8a ins=0x6152
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01fac ins=0x6911
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01e06 ins=0x6171
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01e22 ins=0x8571
<7>ksound: Set parameters for hw:0,2 to 2 x 48000hz with period 1536 (of 4608)
<7>ksound: Set parameters for hw:0,1 to 2 x 48000hz with period 1536 (of 4608)
<7>ksound: Set parameters for hw:0,0 to 2 x 48000hz with period 1536 (of 4608)
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03f12 ins=0x6551
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fefd0 ins=0x8501
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01fac ins=0x6911
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01e06 ins=0x6171
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a01e22 ins=0x8571
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03f12 ins=0x6551
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fefd0 ins=0x8501
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fef8a ins=0x6152
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02ec8 ins=0x6051
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02ec8 ins=0x6051
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02ec8 ins=0x6051
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03054 ins=0x6911
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02f28 ins=0x8511
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02ec8 ins=0x6051
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02ec8 ins=0x6051
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02ec8 ins=0x6051
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02ec8 ins=0x6051
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03054 ins=0x6911
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02f28 ins=0x8511
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02ec8 ins=0x6051
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03054 ins=0x6911
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02f28 ins=0x8511
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02ec8 ins=0x6051
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03054 ins=0x6911
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02f28 ins=0x8511
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a02ec8 ins=0x6051
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x29a03f12 ins=0x6551
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fefd0 ins=0x8501
<5>Unaligned userspace access in "enigma2" pid=1195 pc=0x299fef8a ins=0x6152
<4>aotom_write_rtc 10 - aotom_write_rtc -> 1535294889
```

**Comment by norhap** [comment]
that crash is because it does not find the vkey_"png-s", now they must be housed in buttons folder of each skin, the author of the **LiteHD** skin must give the necessary support.

Here is the example of support:

https://github.com/littlesat/skin-PLiHD/commit/377361fadcda1f43734c2cacdcc1e6c866e9f235

**Comment by littlesat** [comment]
Should be solved in between
