### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by kueken** [OpenPLi/enigma2#1802]
```
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 69, in action
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 49, in action
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SoftwareManager/plugin.py", line 263, in go
    self.session.open(MessageBox, _("Sorry, %s has not been installed!") % ("MediaScanner"), MessageBox.TYPE_INFO, timeout = 10)
  File "/usr/lib/enigma2/python/mytest.py", line 295, in open
    raise RuntimeError("modal open are allowed only from a screen which is modal!")
RuntimeError: modal open are allowed only from a screen which is modal!
```
try open local ipk

**Comment by WanWizard** [comment]
Please report it in the forum.
